import type { Framework } from '@seo/core'
import type { FileChange } from '../engine.js'
import { headStrategyFor, type ReadRepoFile } from '../framework/detect.js'
import { HEAD_FILES } from './inject.js'

/**
 * Edit an existing JSON-LD block in place, rather than adding a second one.
 *
 * The head injector adds markup; this adds *properties to markup that is already there*, and the
 * distinction is the whole reason this file exists. Two LocalBusiness blocks on one page describe
 * two businesses, so "add a block carrying the missing properties" would turn a thin entity into a
 * duplicated one, which is worse than what it set out to fix.
 *
 * It is deterministic in the same way the injector is: it finds a real `<script
 * type="application/ld+json">`, parses it as JSON, and rewrites it only if the parse succeeded and
 * a matching node was found. A block it cannot parse is left alone and the caller reports that
 * honestly, because a half-understood edit to structured data is how a site loses a rich result.
 *
 * The limitation is worth stating plainly: it can only see files it can name (see `HEAD_FILES`),
 * so markup generated by a plugin, a CMS or a component the reader cannot guess is out of reach.
 * That returns null, the fix job records why, and the finding stays open with its guidance. This
 * is the case our own LOCAL-001 fixer produces, so the common path is a block we wrote ourselves.
 */

type JsonObject = Record<string, unknown>

/** One `<script type="application/ld+json">` block, with the offsets of its contents. */
interface JsonLdBlock {
  start: number
  end: number
  json: unknown
  /** The exact whitespace the original block used, so a rewrite reads as a hand edit. */
  indent: string
}

const SCRIPT = /<script\b[^>]*type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi

/** Every parseable JSON-LD block in a file, in order. Unparseable blocks are skipped. */
function blocksIn(content: string): JsonLdBlock[] {
  const blocks: JsonLdBlock[] = []

  for (const match of content.matchAll(SCRIPT)) {
    const body = match[1] ?? ''
    const start = (match.index ?? 0) + match[0].indexOf(body)

    try {
      blocks.push({
        start,
        end: start + body.length,
        json: JSON.parse(body) as unknown,
        indent: /\n([ \t]+)/.exec(body)?.[1] ?? '  ',
      })
    } catch {
      // A block that does not parse is invisible to Google anyway, and guessing at its intent
      // is exactly what a deterministic fixer must not do.
      continue
    }
  }

  return blocks
}

/** Walk a parsed block's nodes, including `@graph` containers, in place. */
function nodesOf(value: unknown, out: JsonObject[] = []): JsonObject[] {
  if (Array.isArray(value)) {
    value.forEach((entry) => nodesOf(entry, out))
    return out
  }
  if (value && typeof value === 'object') {
    const node = value as JsonObject
    if ('@graph' in node) nodesOf(node['@graph'], out)
    out.push(node)
  }
  return out
}

/**
 * Add properties to the first JSON-LD node a predicate matches, in the first head file that has
 * one, and return the whole-file change.
 *
 * Only absent properties are added: a node that already carries one keeps whatever value the site
 * chose, so running this twice changes nothing the second time and an editorial decision is never
 * overwritten. Returns null when no file, no block, or no matching node was found, and when there
 * was nothing left to add.
 */
export async function addJsonLdProperties(
  framework: Framework,
  read: ReadRepoFile,
  matches: (node: JsonObject) => boolean,
  properties: Record<string, unknown>,
): Promise<FileChange | null> {
  for (const path of HEAD_FILES[headStrategyFor(framework)]) {
    const content = await read(path)
    if (content === null) continue

    for (const block of blocksIn(content)) {
      const node = nodesOf(block.json).find(matches)
      if (!node) continue

      const missing = Object.entries(properties).filter(([key]) => node[key] === undefined)
      if (missing.length === 0) return null // already linked; nothing to change

      for (const [key, value] of missing) node[key] = value

      // Re-serialised with the block's own indentation, so the diff shows the added lines rather
      // than a whole-block reformat that a reviewer would have to read character by character.
      const rewritten = JSON.stringify(block.json, null, block.indent.length)
      return {
        path,
        content: content.slice(0, block.start) + `\n${rewritten}\n` + content.slice(block.end),
      }
    }
  }

  return null
}
