import type { Finding } from '@seo/core'
import { describe, expect, it } from 'vitest'
import type { ReadRepoFile } from '../src/framework/detect.js'
import { UnblockAiCrawlersFixer } from '../src/fixers/ai-crawlers.js'
import { makeFinding } from './fixtures.js'

function reader(files: Record<string, string>): ReadRepoFile {
  return async (path) => (path in files ? files[path]! : null)
}

/** A TECH-002 finding blocking OAI-SearchBot and PerplexityBot, as the rule records it. */
function blockedFinding(overrides: Partial<Finding> = {}): Finding {
  return makeFinding({
    ruleId: 'TECH-002',
    title: 'robots.txt blocks OAI-SearchBot and PerplexityBot',
    affectedUrls: ['https://ex.com/'],
    evidence: {
      kind: 'markup',
      url: 'https://ex.com/',
      locator: '/robots.txt',
      snippet:
        'Disallowed: OAI-SearchBot (OpenAI). Removed from ChatGPT answers.\n' +
        'Disallowed: PerplexityBot (Perplexity). Removed from Perplexity answers.',
      observedAt: '2026-07-19T00:00:00.000Z',
      source: 'crawler',
    },
    ...overrides,
  })
}

const fixer = new UnblockAiCrawlersFixer()

describe('UnblockAiCrawlersFixer', () => {
  it('flips a named agent group from Disallow to Allow, in place', async () => {
    const robots = [
      'User-agent: OAI-SearchBot',
      'Disallow: /',
      '',
      'User-agent: PerplexityBot',
      'Disallow: /',
      '',
      'User-agent: *',
      'Allow: /',
      'Sitemap: https://ex.com/sitemap.xml',
      '',
    ].join('\n')

    const result = await fixer.generate({
      finding: blockedFinding(),
      framework: 'react_spa',
      read: reader({ 'public/robots.txt': robots }),
    })

    expect(result).not.toBeNull()
    const content = result!.files[0]!.content
    expect(result!.files[0]!.path).toBe('public/robots.txt')
    // Both named groups now allow the root, and no Disallow: / remains.
    expect(content).not.toMatch(/Disallow:\s*\/$/m)
    expect(content).toMatch(/User-agent: OAI-SearchBot\nAllow: \//)
    expect(content).toMatch(/User-agent: PerplexityBot\nAllow: \//)
    // The wildcard group and the sitemap are untouched.
    expect(content).toContain('Sitemap: https://ex.com/sitemap.xml')
  })

  it('appends a specific allow group when the agent is only caught by the wildcard', async () => {
    const robots = ['User-agent: *', 'Disallow: /', ''].join('\n')

    const result = await fixer.generate({
      finding: blockedFinding({
        evidence: {
          kind: 'markup',
          url: 'https://ex.com/',
          locator: '/robots.txt',
          snippet: 'Disallowed: OAI-SearchBot (OpenAI). Removed from ChatGPT answers.',
          observedAt: '2026-07-19T00:00:00.000Z',
          source: 'crawler',
        },
      }),
      framework: 'react_spa',
      read: reader({ 'robots.txt': robots }),
    })

    expect(result).not.toBeNull()
    const content = result!.files[0]!.content
    // The wildcard block is left as the human wrote it; a more specific group overrides it.
    expect(content).toContain('User-agent: *\nDisallow: /')
    expect(content).toMatch(/User-agent: OAI-SearchBot\nAllow: \//)
  })

  it('returns null when robots.txt is generated by code, not a file', async () => {
    // A Next.js robots.ts route: nothing safe to string-edit here.
    const result = await fixer.generate({
      finding: blockedFinding(),
      framework: 'next',
      read: reader({ 'app/robots.ts': 'export default function robots() { return {} }' }),
    })
    expect(result).toBeNull()
  })

  it('does nothing when the finding names no blocked agents', () => {
    const finding = blockedFinding({
      evidence: {
        kind: 'markup',
        url: 'https://ex.com/',
        locator: '/robots.txt',
        snippet: '',
        observedAt: '2026-07-19T00:00:00.000Z',
        source: 'crawler',
      },
    })
    expect(fixer.canFix(finding)).toBe(false)
  })

  it('ignores findings from other rules', () => {
    expect(fixer.canFix(makeFinding({ ruleId: 'TECH-007' }))).toBe(false)
  })
})
